update pipeline

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -9,14 +9,28 @@ env:
   REGION: us-central1
   CLUSTER_NAME: devops-gke
   REPO_NAME: devops-repo
+  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
 
 jobs:
   build-deploy:
     runs-on: ubuntu-latest
 
     steps:
+
     - name: Checkout Repository
       uses: actions/checkout@v3
+
+
+    - name: Build Backend Image
+      run: |
+        SHA=${{ github.sha }}
+        docker build -t backend:$SHA ./backend
+
+    - name: Build Frontend Image
+      run: |
+        SHA=${{ github.sha }}
+        docker build -t frontend:$SHA ./frontend
+
     - name: Authenticate to GCP
       uses: google-github-actions/auth@v2
       with:
@@ -25,23 +39,25 @@ jobs:
     - name: Setup gcloud CLI
       uses: google-github-actions/setup-gcloud@v2
 
+
     - name: Configure Docker for Artifact Registry
       run: |
         gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
-    - name: Build & Push Backend Image
+
+    - name: Tag and Push Backend Image
       run: |
         SHA=${{ github.sha }}
-        IMAGE=$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/$REPO_NAME/backend:$SHA
+        IMAGE=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/backend:$SHA
 
-        docker build -t $IMAGE ./backend
+        docker tag backend:$SHA $IMAGE
         docker push $IMAGE
 
-    - name: Build & Push Frontend Image
+    - name: Tag and Push Frontend Image
       run: |
         SHA=${{ github.sha }}
-        IMAGE=$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/$REPO_NAME/frontend:$SHA
+        IMAGE=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/frontend:$SHA
 
-        docker build -t $IMAGE ./frontend
+        docker tag frontend:$SHA $IMAGE
         docker push $IMAGE
     - name: Install Helm
       uses: azure/setup-helm@v3
@@ -49,7 +65,7 @@ jobs:
     - name: Update Helm values with new image tag
       run: |
         SHA=${{ github.sha }}
-        sed -i "s/tag: \"latest\"/tag: \"$SHA\"/g" helm-chart/devops-app/values.yaml
+        sed -i "s/tag:.*/tag: \"$SHA\"/g" helm-chart/devops-app/values.yaml
 
     - name: Package Helm Chart
       run: |
@@ -64,43 +80,30 @@ jobs:
     - name: Push Helm Chart to Artifact Registry
       run: |
         helm push devops-app-0.1.0.tgz \
-          oci://$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/$REPO_NAME
+        oci://$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME
 
     - name: Check if GKE Cluster Exists
-      id: check_gke
       run: |
-        if gcloud container clusters describe $CLUSTER_NAME \
+        if ! gcloud container clusters describe $CLUSTER_NAME \
           --region $REGION \
-          --project ${{ secrets.GCP_PROJECT }} > /dev/null 2>&1; then
-          echo "exists=true" >> $GITHUB_OUTPUT
-        else
-          echo "exists=false" >> $GITHUB_OUTPUT
+          --project $PROJECT_ID
+        then
+          echo "GKE cluster not found. Failing pipeline."
+          exit 1
         fi
 
-    - name: Setup Terraform
-      if: steps.check_gke.outputs.exists == 'false'
-      uses: hashicorp/setup-terraform@v3
-
-    - name: Terraform Init & Apply (Create GKE if not exists)
-      if: steps.check_gke.outputs.exists == 'false'
-      run: |
-        cd terraform
-        terraform init
-        terraform apply -auto-approve \
-          -var="project_id=${{ secrets.GCP_PROJECT }}" \
-          -var="region=$REGION"
 
     - name: Get GKE Credentials
       run: |
         gcloud container clusters get-credentials $CLUSTER_NAME \
           --region $REGION \
-          --project ${{ secrets.GCP_PROJECT }}
+          --project $PROJECT_ID
 
-    - name: Pull Helm Chart from Artifact Registry
+    - name: Pull Helm Chart
       run: |
         helm pull \
-          oci://$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/$REPO_NAME/devops-app \
-          --version 0.1.0
+        oci://$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/devops-app \
+        --version 0.1.0
 
     - name: Deploy Helm Release
       run: |
